# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs thatipython can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  convert:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:    
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: rename files/folders
      run: |
        tree
        set -x
        sudo apt-get install rename
        find -name "* *" -type d | rename 's/ /-/g'
        find -name "* *" -type f | rename 's/ /-/g'
        tree
    #- name: delete md
    #  run: dir #rm _notebooks/**/*.md
    - name: instal
      run: |
        pip3 install --upgrade pip
        pip3 install jupyter
    - name: Install nbconvert
      run: pip3 install nbconvert
    - name: convert to markdown
      run: jupyter nbconvert --to markdown ./**/*.ipynb
    - name: list
      run: tree
    - name: commit
      run: |
        git config --global user.email "v986963@gmail.com"
        git config --global user.name "vosaul"
        git add *
        git commit -m "converted to markdown"
#    - name: Archive production artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: dist with-markdown
#        path: |
#          ./**/*.md
#    - name: Archive code coverage results
#      uses: actions/upload-artifact@v2
#      with:
#        name: code-coverage-report
#        path: ./**/*.md

